apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventhub-frontend
  namespace: eventhub
  labels:
    app: eventhub-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventhub-frontend
  template:
    metadata:
      labels:
        app: eventhub-frontend
    spec:
      containers:
        - name: eventhub-frontend-container
          image: "docker.io/manvendraniranjan528/eventhub-frontend:1.0.0"
          ports:
            - containerPort: 8080      
